[build]
  command = ""      # žádný build
  publish = "./"    # publikuj rovnou root složku

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
  Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
